//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaPlayer.VideoProcessingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFAIOProcessor")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VideoProcessingService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProcessVideo", ReplyAction="http://tempuri.org/IService1/ProcessVideoResponse")]
        string[] ProcessVideo(string location, bool withAudio, double startDuration, double endDuration, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFramesList", ReplyAction="http://tempuri.org/IService1/GetFramesListResponse")]
        string GetFramesList(string videoName, string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProcessVideo2", ReplyAction="http://tempuri.org/IService1/ProcessVideo2Response")]
        string[] ProcessVideo2(string location, bool withAudio, string ID, bool scale, int width, int height, float FPS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckEndFrame", ReplyAction="http://tempuri.org/IService1/CheckEndFrameResponse")]
        string CheckEndFrame(string videoURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MediaPlayer.VideoProcessingService.CompositeType GetDataUsingDataContract(MediaPlayer.VideoProcessingService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MediaPlayer.VideoProcessingService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MediaPlayer.VideoProcessingService.IService1>, MediaPlayer.VideoProcessingService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ProcessVideo(string location, bool withAudio, double startDuration, double endDuration, string ID) {
            return base.Channel.ProcessVideo(location, withAudio, startDuration, endDuration, ID);
        }
        
        public string GetFramesList(string videoName, string sessionID) {
            return base.Channel.GetFramesList(videoName, sessionID);
        }
        
        public string[] ProcessVideo2(string location, bool withAudio, string ID, bool scale, int width, int height, float FPS) {
            return base.Channel.ProcessVideo2(location, withAudio, ID, scale, width, height, FPS);
        }
        
        public string CheckEndFrame(string videoURL) {
            return base.Channel.CheckEndFrame(videoURL);
        }
        
        public MediaPlayer.VideoProcessingService.CompositeType GetDataUsingDataContract(MediaPlayer.VideoProcessingService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
